### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by badrul1** [PropelAuth/react-frontend-starter#2]
Ok I m getting this error when trying to run the starter example. Will update if I fix it.
The backend (http://127.0.0.1:3001) is running and the front end starts but gives me the error below when i try to go to .
http://localhost:3000 or http://192.168.0.107:3000
```
ERROR
Failed to fetch
TypeError: Failed to fetch
    at fetchAuthenticationInfo (http://192.168.0.107:3000/static/js/bundle.js:1341:10)
    at forceRefreshToken (http://192.168.0.107:3000/static/js/bundle.js:1566:40)
    at Object.getAuthenticationInfoOrNull (http://192.168.0.107:3000/static/js/bundle.js:1640:22)
    at onOnlineOrFocus (http://192.168.0.107:3000/static/js/bundle.js:1730:20)
```

**Comment by badrul1** [comment]
Ok some additional notes that aren't documented in the tutorial.
1. Make sure you have a .env file in the backend folder. It should contain:
PROPELAUTH_AUTH_URL=XXX
PROPELAUTH_API_KEY=XXX

(and possibly...)
2. Add 'http://localhost:3000' to 'Additional Frontend Locations' in the 'Frontend integration' part of the ProperlAuth website. This is to get around the CORS error
